### PR TITLE
Add support for Keyvaluemap access.

### PR DESCRIPTION
**Pull request by prao-api**
Adding the new code for KeyValueMap access.

### CODE REVIEW

**Comment by prao-api** [comment]
@gbrail please review and merge.

**Comment by gbrail** [comment]
Don't we need a change in index.js so that you can actually get to "getKeyValueMap"? That's what we did for the other stuff.

**Review by gbrail — CHANGES_REQUESTED** [review]
Don't we need a change in index.js so that you can actually get to "getKeyValueMap"? That's what we did for the other stuff.

**Comment by gbrail** [comment]
So to be clear, I think that we also changed index.js to make it possible to get a KVM, but that change isn't in this PR.

**Comment by prao-api** [comment]
@gbrail - My bad. I have added the changes to index.js. Thank you.

**Comment by DinoChiesa** [comment]
@gbrail - And do we need a version bump?

The version is 1.3.0 without keyvaluemap.js


I suppose we want 1.3.1 or 1.4.0 WITH keyvaluemap.js

________________________________

**Comment by DinoChiesa** [comment]
Still need the version update in package.json !

**Pull request merged**
